## Парсинг 250 фильмов из кинопоиска с помощью апи

### Ключ с помощью которого можно обратиться к апи:

In [1]:
# импорт необходимых библиотек

In [2]:
import requests
import pandas as pd

In [3]:
TOKEN = 'ASW159B-1RX4B52-HJ2HQAE-JPB0MCA' 
API_URL = 'https://api.poiskkino.dev/v1.4/movie'
FILE_NAME = '250ruFilm.csv' 

headers = {'X-API-KEY': TOKEN}

params = {
    'limit': 250,
    'type': 'movie',
    'countries.name': ['!Россия', '!СССР'],
    'sortField': 'rating.kp',
    'sortType': '-1',
    'votes.kp': '100000-10000000',
    'selectFields': ['name', 'alternativeName', 'description', 'year', 'countries', 'genres']
}

response = requests.get(API_URL, headers=headers, params=params)

if response.status_code == 200:
    api_data = response.json().get('docs', [])
    
    foreign_movies = []
    for m in api_data:
        foreign_movies.append({
            'name': m.get('name') or m.get('alternativeName'),
            'description': m.get('description') or 'Нет описания',
            'country': ', '.join([c['name'] for c in m.get('countries', [])]),
            'year': m.get('year'),
            'genre': ', '.join([g['name'] for g in m.get('genres', [])])
        })

    df_foreign = pd.DataFrame(foreign_movies)
    df_russian = pd.read_csv(FILE_NAME)
    df_final = pd.concat([df_russian, df_foreign], ignore_index=True)
    df_final.to_csv(FILE_NAME, index=False, encoding='utf-8-sig')
    print(f"Успех")
        
else:
    print(f"Ошибка {response.status_code}")

Успех

In [5]:
df= pd.read_csv('250ruFilm.csv')

In [6]:
df

,Unnamed: 0,name,description,country,year,genre
0,0.0,Сестрёнка,Экранизация повести Мустая Карима “Радость наш...,Россия,2019.0,"военный фильм, драма"
1,1.0,Шугалей-3,После долгого плена в ливийской тюрьме «Митига...,Россия,2021.0,"боевик, приключения"
2,2.0,Женская логика - 1,По мотивам одноименного романа Виктора Пронина...,Россия,2002.0,"детектив, экранизация"
3,3.0,Доктор,"Основано на реальных событиях, по документальн...",Россия,2022.0,драма
4,4.0,Жили-были,Старинная деревня в русской глубинке. Из жител...,Россия,2017.0,мелодрама
...,...,...,...,...,...,...
495,NaN,Гнев,Состоятельные жители Мехико в панике: всего за...,"США, Великобритания",2004.0,"боевик, триллер, драма, криминал"
496,NaN,Гангстер,"После смерти хозяина, Фрэнк Лукас, тихий водит...","США, Великобритания",2007.0,"драма, криминал, биография"
497,NaN,Гаттака,Добро пожаловать в Гаттаку - совершенный мир б...,США,1997.0,"фантастика, драма, мелодрама, детектив"
498,NaN,Исчезнувшая,Всё было готово для празднования пятилетия суп...,США,2014.0,"триллер, драма, детектив"
499,NaN,Кокаин,"Джордж Джанг, обыкновенный парень из пригорода...",США,2001.0,"криминал, биография, драма"

In [9]:
df.drop(columns=['Unnamed: 0'])

,name,description,country,year,genre
0,Сестрёнка,Экранизация повести Мустая Карима “Радость наш...,Россия,2019.0,"военный фильм, драма"
1,Шугалей-3,После долгого плена в ливийской тюрьме «Митига...,Россия,2021.0,"боевик, приключения"
2,Женская логика - 1,По мотивам одноименного романа Виктора Пронина...,Россия,2002.0,"детектив, экранизация"
3,Доктор,"Основано на реальных событиях, по документальн...",Россия,2022.0,драма
4,Жили-были,Старинная деревня в русской глубинке. Из жител...,Россия,2017.0,мелодрама
...,...,...,...,...,...
495,Гнев,Состоятельные жители Мехико в панике: всего за...,"США, Великобритания",2004.0,"боевик, триллер, драма, криминал"
496,Гангстер,"После смерти хозяина, Фрэнк Лукас, тихий водит...","США, Великобритания",2007.0,"драма, криминал, биография"
497,Гаттака,Добро пожаловать в Гаттаку - совершенный мир б...,США,1997.0,"фантастика, драма, мелодрама, детектив"
498,Исчезнувшая,Всё было готово для празднования пятилетия суп...,США,2014.0,"триллер, драма, детектив"
499,Кокаин,"Джордж Джанг, обыкновенный парень из пригорода...",США,2001.0,"криминал, биография, драма"